# Generated by Django 4.2.13 on 2024-05-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishingredient",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_ingredients",
                to="pizza_delivery.dish",
            ),
        ),
        migrations.AlterField(
            model_name="dishingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_dishes",
                to="pizza_delivery.ingredient",
            ),
        ),
    ]
