# Generated by Django 4.2.13 on 2024-05-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
